        <!--
            jQuery
        --------------------------------->
        <script src="http://code.jquery.com/jquery-2.0.3.min.js"></script>
        <script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>

        <!--
            jQueryUI
        --------------------------------->
        <link rel="stylesheet" href="//code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.9.1.js"></script>
        <script src="//code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
        
        <!--
            jqModal
        --------------------------------->
        <link rel="stylesheet" href="/css/jqModal.css">
        <script src="js/jqModal.js"></script>
        
        <!--
            spin.js
        --------------------------------->
        <script src="js/spin.js"></script>
        

        <!--
            Twitter Bootstrap
        --------------------------------->
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css">
        <!-- Optional theme -->
        <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.min.css">
        <!-- Latest compiled and minified JavaScript -->
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
        
        <!-- Leaflet
        --------------------------------->
        <link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.css" />
        <script src="http://cdn.leafletjs.com/leaflet-0.7.2/leaflet.js"></script>
        
        <!--
            leaflet.spin.js
        --------------------------------->
        <script src="js/leaflet.spin.js"></script>
        
        
        <!-- Google Web Fonts
        ---------------------------------->
        <link href="http://fonts.googleapis.com/css?family=Droid+Serif" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Droid+Sans" rel="stylesheet" type="text/css">

        <!--
            leaflet.spin.js
        --------------------------------->
        <script src="js/jquery.tablesorter.min.js"></script>
        <!-- 
            My scripts 
        ----------------------------------->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/changingphl.js')
        ; ?>

        <!--
            My stylesheet
        ----------------------------------->
        <link rel="stylesheet" href="/css/style.css">