<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Philadelphia Construction Permit Heatmap')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->partial("layout/header-includes.phtml"); ?>

        <!--- APPLICATION_ENV
        <?php echo (getenv('APPLICATION_ENV') ?: 'production') . "\n"; ?>
        ------------------------------->
        
        <!--
        <?php echo getcwd(); ?>
        ------------------------------->
    </head>
    <body>
        <?php echo $this->content; ?>
    </body>
    <?php echo $this->partial("layout/google-analytics.phtml"); ?>
</html>
