<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Gentrifying Philly')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->partial("snippets/header-includes.phtml"); ?>

    </head>
    <body>
        
        <?php //echo $this->partial("snippets/navbar.phtml"); ?>

        <?php echo $this->content; ?>
    </body>
    <?php echo $this->partial("snippets/google-analytics.phtml"); ?>
</html>
