<div class='about row'>
    <div class='col-md-6 col-md-offset-3'>
        <h2>About Gentrifying Philly</h2>
        <p>The data was downloaded from the City of Philadelphia's 
            <a href='http://phlapi.com/'>open data portal phlapi.com</a>. Permit codes 
            and descriptions may be <a href='http://phlapi.com/permittypes.html'>found 
                here</a>. Note that having a permit issued to a location means that
                any construction was done.
        </p>

        <p>I chose to count the number of locations that had construction permits 
            issued per neighborhood instead of using the total permits per neighborhood 
            count because I believe it's possible to have blanket permits taken out 
            for large construction permits instead of permits for each alteration type. 
            For example, one neighborhood may have an apartment building under construction with a 
            thousand permits issued while another may have 50 pulled.
        </p>
        <p>
            Contact: <a href='mailto:jim.R.smiley@gmail.com'>jim.R.smiley@gmail.com</a>
        </p>
    </div>
</div>