<div class='about row'>
    <div class='col-md-6 col-md-offset-3'>
        <h2>About Gentrifying Philly</h2>
        <p><a href="/"><- Back to the map</a></p>
        <p>The permit data was downloaded from the City of Philadelphia's 
            <a href='http://phlapi.com/'>open data portal phlapi.com</a>.  From the website:
                
        <blockquote>A permit grants legal permission to commence work on physical 
                changes or zoning changes to a lot or structure. These include 
                but are not limited to new constructions, alterations, demolitions, 
                occupancy changes, and installations of and modifications to 
                electrical, mechanical, and plumbing systems.
        </blockquote>
            Permit codes and descriptions may be <a href='http://phlapi.com/permittypes.html'>found 
            here</a>. I included all permits, including occupancy changes.
            Note that having a permit issued to a location does not necessarily mean that
            any construction was done.
        </p>
        <p>I chose to count the number of locations that had construction permits 
            issued per neighborhood instead of using the total permits per neighborhood 
             because I believe it's possible to have blanket permits taken out 
            for large construction permits instead of permits for each alteration type. 
            For example, one neighborhood may have an apartment building under construction with a 
            thousand permits issued while another may have fifty.
        </p>
        <p>
            Even though the data is straight forward, care needs to be taken 
            when interpreting it. A neighborhood showing a decline over the 
            last year may be just rebounding from a bubble. Brewerytown for 
            instance, shows a 50% drop in locations under construction from 
            2012 to 2013. But it would probably be a mistake to identify 
            Brewerytown as a neighborhood in decline, being so close to 
            Fairmount Park and other improving neighborhoods. Most likely, 
            a large development of many houses went up in 2012 skewing the data.
        </p>
        <p>
            A lot of my motivations for the project came from my experience with 
            community reporting for <a href="http://frankfordgazette.com">The Frankford 
                Gazette</a>. I became very interested in how Philadelphia’s former 
                industrial neighborhoods are changing in the 21st century. And 
                how that change is perceived. To many Northeast 
                Philadelphia residents that I know, Kensington is a dirty word. 
                Many of them grew up there, saw jobs leave, saw crime rise, and 
                left. They think it’s a dive. But I’m not seeing that. And many 
                newcomers and younger residents aren’t seeing that either. They’re 
                looking at Kensington with hope. The same goes for a lot of West 
                Philadelphia and other forgotten neighborhoods. I find that 
                fascinating and wanted to see if I could measure neighborhoods 
                as they change.
        </p>
        <p>
            Much of the project was done at <a href='http://www.meetup.com/Code-for-America-Philly/'>Code for Philly's weekly hack nights.</a>
            I hope to include more historical data as permit data goes back to 2007.
        </p>
        <p>
            Contact:<br/>
            <a href="http://twitter.com/jimRsmiley">@jimRsmiley</a><br/>
            <a href='mailto:jim.R.smiley@gmail.com'>jim.R.smiley@gmail.com</a>
        </p>
        <p><a href="/"><- Back to the map</a></p>
    </div>
</div>