<div>
    
    <div id="map"></div>
    
    <div class="info project-info leaflet-control">
        <div class="credit row">
            <p>A <a href="http://codeforphilly.com/projects/Mapping_gentrification_and_decline_of_Philly_neighborhoods">Code for Philly</a> project by <a href="http://twitter.com/jimRsmiley">@jimRsmiley</a>    </p></div>
            
            <div class="project-description">
                <h2 style="text-align: center">Philadelphia Construction Permits by Neighborhood</h2>
                <p>
                    Can a change in the number of properties issued construction permits over time tell us anything about Philadelphia neighbohroods?   [ <a href="/about">more on the project</a> ]
                </p>
                <p><a href='/average-change'>View a map comparing the last two years against the previous 5 years</a></p>
                <p><a href="/data">View the data in table form</a></p>
            </div>
        
            <div style="padding: 12px 0">
                
                <form>
                    
                    <label>Select a year comparison: </label>
                    
                    <select id="yearselect">
                        <option value='{"method":"year-compare","start":2012,"end":2013}'>2012 to 2013</option>
                        <option value='{"method":"year-compare","start":2011,"end":2012}'>2011 to 2012</option>
                        <option value='{"method":"year-compare","start":2010,"end":2011}'>2010 to 2011</option>
                        <option value='{"method":"year-compare","start":2009,"end":2010}'>2009 to 2010</option>
                        <option value='{"method":"year-compare","start":2008,"end":2009}'>2008 to 2009</option>
                        <option value='{"method":"year-compare","start":2007,"end":2008}'>2007 to 2008</option>
                    </select>
                    
                </form>
                
            </div>
        
            <div class="neighborhood-info"><b>Hover over a neighborhood</b></div>
    </div>
    <div class="info legend leaflet-control">
        <p>Percent Change</p>
        <i style="background:#e31a1c"></i> > 30<br>
        <i style="background:#fd8d3c"></i> 20 to 30<br>
        <i style="background:#fecc5c"></i> 10 to 20<br>
        <i style="background:#ffffb2"></i> 0 to 10<br>
        
        <i style="background:#f1eef6"></i> 0 to -10<br>
        <i style="background:#bdc9e1"></i> -10 to -20<br>
        <i style="background:#74a9cf"></i> -20 to -30<br>
        <i style="background:#0570b0"></i> < -30
    </div>
</div>

<script>
$( document ).ready( function() {
   
    var map = new YearlyChangeMap('map');
    map.loadDataM();
});
</script>
